### PR TITLE
Clean up

### PR DESCRIPTION
**Pull request by 191220029**

### CODE REVIEW

**Review by aminya — CHANGES_REQUESTED** [review]
Why archiving the code?

**Comment by 191220029** [comment]
> Why archiving the code?

Hello, there. We are planning to refactor the Dagrs with Flow-based Programming Paradigm. And here is our plan

**Comment by 191220029** [comment]
> Why archiving the code?

We are planning to refactor Dagrs using the flow-based programming paradigm. Our plan is as follows
https://docs.google.com/presentation/d/1UP3OlzJwP9pjBcbASys3m-gQP7MlONyU/edit?usp=sharing&ouid=109824571352106516794&rtpof=true&sd=true

**Review by genedna — APPROVED** [review]

**Comment by 191220029** [comment]
And we also provide a brief introduction about our plan in docs/upgrade.md
Welcome to join our discord channel to discuss about the refactoration: https://discord.gg/xaHZXwnn

**Comment by aminya** [comment]
I think it's better to do this in a temporary `dev` branch instead of the actual main branch in case we have to apply fixes to the `main` while development happens.

**Comment by genedna** [comment]
> I think it's better to do this in a temporary `dev` branch instead of the actual main branch in case we have to apply fixes to the `main` while development happens.

I am a fan of [trunk-base development](https://trunkbaseddevelopment.com), and I hope to rewrite dagrs from the beginning and cross-review each PR to help the engine have better code quality.

**Comment by genedna** [comment]
#70

**Comment by aminya** [comment]
So if you don't wanna keep the original code in main and start a new branch, why not just remove the current code. Why move them?

**Review by A-Mavericks — APPROVED** [review]

**Pull request merged**
